### ISSUE TITLE
More info needed about AI architecture 

### ISSUE THREAD

**Issue by questsin** [lakinwecker/delila#6]
How would the AI look for motif etc?

**Comment by lakinwecker** [comment]
I wouldn't call this AI, but that's fine. Also all of that will likely be implemented in https://github.com/lakinwecker/samson

**Comment by lakinwecker** [comment]
https://github.com/lakinwecker/samson/issues/2 <- you can follow the discussion there. I'm pretty far away from actually implementing this though.
